server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mytest?useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.ajavac.domain
  mapper-locations: mapper/*.xml